@echo off

ren "alexkidd.png" "Alex Kidd.png"
ren "alien.png" "Alien.png"
ren "aliens.png" "Aliens.png"
ren "aof.png" "Aof.png"
ren "assassinscreed.png" "Assassins Creed.png"
ren "asterix.png" "Asterix.png"
ren "batman.png" "Batman.png"
ren "battletoads.png" "Battletoads.png"
ren "beatmup.png" "Beatm Up.png"
ren "bomberman.png" "Bomberman.png"
ren "burnout.png" "Burnout.png"
ren "callofduty.png" "Call Of Duty.png"
ren "castlevania.png" "Castlevania.png"
ren "collections.png" "Collections.png"
ren "contra.png" "Contra.png"
ren "crashbandicoot.png" "Crash Bandicoot.png"
ren "darius.png" "Darius.png"
ren "darkstalkers.png" "Darkstalkers.png"
ren "dbz.png" "Dbz.png"
ren "deadoralive.png" "Dead Or Alive.png"
ren "devilmaycry.png" "Devil May Cry.png"
ren "disney.png" "Disney.png"
ren "donkeykong.png" "Donkey Kong.png"
ren "doom.png" "Doom.png"
ren "doubledragon.png" "Double Dragon.png"
ren "dragonquest.png" "Dragon Quest.png"
ren "dukenukem.png" "Duke Nukem.png"
ren "earthworm.png" "Earthworm.png"
ren "earthwormjim.png" "Earthworm Jim.png"
ren "fatalfury.png" "Fatal Fury.png"
ren "finalfantasy.png" "Final Fantasy.png"
ren "finalfight.png" "Final Fight.png"
ren "fzero.png" "Fzero.png"
ren "ghostbusters.png" "Ghostbusters.png"
ren "ghoulsandghosts.png" "Ghouls And Ghosts.png"
ren "goldenaxe.png" "Golden Axe.png"
ren "gow.png" "Gow.png"
ren "granturismo.png" "Gran Turismo.png"
ren "gta.png" "Gta.png"
ren "guiltygear.png" "Guilty Gear.png"
ren "halo.png" "Halo.png"
ren "harrypotter.png" "Harry Potter.png"
ren "houseofthedead.png" "House Of The Dead.png"
ren "jamesbond.png" "James Bond.png"
ren "jurassicpark.png" "Jurassic Park.png"
ren "killerinstinct.png" "Killer Instinct.png"
ren "kof.png" "Kof.png"
ren "lemmings.png" "Lemmings.png"
ren "mario.png" "Mario.png"
ren "megaman.png" "Megaman.png"
ren "metalgear.png" "Metal Gear.png"
ren "metalslug.png" "Metal Slug.png"
ren "metroid.png" "Metroid.png"
ren "mortalkombat.png" "Mortal Kombat.png"
ren "nba.png" "Nba.png"
ren "needforspeed.png" "Need For Speed.png"
ren "outrun.png" "Outrun.png"
ren "pacman.png" "Pacman.png"
ren "pokemon.png" "Pokemon.png"
ren "quake.png" "Quake.png"
ren "rayman.png" "Rayman.png"
ren "residentevil.png" "Resident Evil.png"
ren "robocop.png" "Robocop.png"
ren "samuraishodown.png" "Samurai Shodown.png"
ren "shiningforce.png" "Shining Force.png"
ren "silenthill.png" "Silent Hill.png"
ren "simpsons.png" "Simpsons.png"
ren "sonic.png" "Sonic.png"
ren "spaceinvaders.png" "Space Invaders.png"
ren "spiderman.png" "Spiderman.png"
ren "spyro.png" "Spyro.png"
ren "starfox.png" "Starfox.png"
ren "starwars.png" "Starwars.png"
ren "streetfighter.png" "Streetfighter.png"
ren "tekken.png" "Tekken.png"
ren "tmnt.png" "Tmnt.png"
ren "toki.png" "Toki.png"
ren "tombraider.png" "Tomb Raider.png"
ren "transformers.png" "Transformers.png"
ren "virtuafighter.png" "Virtua Fighter.png"
ren "xmen.png" "Xmen.png"
ren "yoshi.png" "Yoshi.png"
ren "zelda.png" "Zelda.png"